Repository apace100/apoli, pull requests merged in 2024-05, with the labels that each got.

#180 Add stuff related to command tags
  src/main/java/io/github/apace100/apoli/Apoli.java
  src/main/java/io/github/apace100/apoli/data/ApoliDataHandlers.java
  src/main/java/io/github/apace100/apoli/mixin/EntityAccessor.java
  src/main/java/io/github/apace100/apoli/mixin/EntityMixin.java
  src/main/java/io/github/apace100/apoli/power/factory/condition/EntityConditions.java
  src/main/java/io/github/apace100/apoli/power/factory/condition/entity/HasCommandTagCondition.java
Labels: to merge

#231 Make the `*_block_use` power types consistent with the `*_entity_use` power types
  src/main/java/io/github/apace100/apoli/data/ApoliDataTypes.java
  src/main/java/io/github/apace100/apoli/mixin/ClientPlayerInteractionManagerMixin.java
  src/main/java/io/github/apace100/apoli/mixin/ServerPlayerInteractionManagerMixin.java
  src/main/java/io/github/apace100/apoli/power/ActionOnBlockUsePower.java
  src/main/java/io/github/apace100/apoli/power/PreventBlockUsePower.java
  src/main/java/io/github/apace100/apoli/power/Prioritized.java
  src/main/java/io/github/apace100/apoli/util/ActionResultUtil.java
  src/main/java/io/github/apace100/apoli/util/BlockUsagePhase.java
  src/main/java/io/github/apace100/apoli/util/PriorityPhase.java
Labels: to-merge

#229 Add `click_phase` and `priority` fields to `item_on_item` power type
  src/main/java/io/github/apace100/apoli/data/ApoliDataTypes.java
  src/main/java/io/github/apace100/apoli/mixin/ItemMixin.java
  src/main/java/io/github/apace100/apoli/mixin/ItemStackMixin.java
  src/main/java/io/github/apace100/apoli/mixin/ScreenHandlerAccessor.java
  src/main/java/io/github/apace100/apoli/power/ItemOnItemPower.java
  src/main/java/io/github/apace100/apoli/util/StackClickPhase.java
  src/main/resources/apoli.mixins.json
Labels: to-merge

#192 Add `show_toast` entity action type
  build.gradle
  src/main/java/io/github/apace100/apoli/access/CustomToastViewer.java
  src/main/java/io/github/apace100/apoli/data/CustomToastData.java
  src/main/java/io/github/apace100/apoli/mixin/ClientPlayerEntityMixin.java
  src/main/java/io/github/apace100/apoli/mixin/ServerPlayerEntityMixin.java
  src/main/java/io/github/apace100/apoli/mixin/ToastManagerEntryMixin.java
  src/main/java/io/github/apace100/apoli/networking/ModPacketsS2C.java
  src/main/java/io/github/apace100/apoli/networking/packet/s2c/ShowToastS2CPacket.java
  src/main/java/io/github/apace100/apoli/power/factory/action/EntityActions.java
  src/main/java/io/github/apace100/apoli/power/factory/action/entity/ShowToastAction.java
  src/main/java/io/github/apace100/apoli/screen/toast/CustomToast.java
  src/main/java/io/github/apace100/apoli/screen/toast/PositionAwareToast.java
  src/main/resources/apoli.accesswidener
  src/main/resources/apoli.mixins.json
  src/main/resources/assets/apoli/textures/gui/sprites/toast/custom.png
  src/main/resources/assets/apoli/textures/gui/sprites/toast/custom.png.mcmeta
Labels: to-merge

#211 Add `modify_fov` power type
  src/main/java/io/github/apace100/apoli/mixin/AbstractClientPlayerEntityMixin.java
  src/main/java/io/github/apace100/apoli/power/ModifyFovPower.java
  src/main/java/io/github/apace100/apoli/power/factory/PowerFactories.java
  src/main/resources/apoli.mixins.json
Labels: to-merge

#226 Add `entity_in_radius` entity condition type
  src/main/java/io/github/apace100/apoli/power/factory/condition/EntityConditions.java
  src/main/java/io/github/apace100/apoli/power/factory/condition/entity/EntityInRadiusCondition.java
Labels: to-merge

#219 Add item action/condition types related to item cooldowns
  src/main/java/io/github/apace100/apoli/power/factory/action/ItemActions.java
  src/main/java/io/github/apace100/apoli/power/factory/action/item/ModifyItemCooldownAction.java
  src/main/java/io/github/apace100/apoli/power/factory/condition/ItemConditions.java
  src/main/java/io/github/apace100/apoli/power/factory/condition/item/ItemCooldownCondition.java
  src/main/java/io/github/apace100/apoli/power/factory/condition/item/RelativeItemCooldownCondition.java
  src/main/resources/apoli.accesswidener
Labels: enhancement, to-merge

#224 Rename and add alias for `apoli:entity_set` related Conditions and Actions
  src/main/java/io/github/apace100/apoli/power/factory/action/BiEntityActions.java
  src/main/java/io/github/apace100/apoli/power/factory/action/EntityActions.java
  src/main/java/io/github/apace100/apoli/power/factory/action/bientity/AddToEntitySetAction.java
  src/main/java/io/github/apace100/apoli/power/factory/action/bientity/RemoveFromEntitySetAction.java
  src/main/java/io/github/apace100/apoli/power/factory/action/entity/ActionOnEntitySetAction.java
  src/main/java/io/github/apace100/apoli/power/factory/condition/BiEntityConditions.java
  src/main/java/io/github/apace100/apoli/power/factory/condition/EntityConditions.java
  src/main/java/io/github/apace100/apoli/power/factory/condition/bientity/InEntitySetCondition.java
  src/main/java/io/github/apace100/apoli/power/factory/condition/entity/EntitySetSizeCondition.java
Labels: to-merge
